### ISSUE TITLE
Stuck on, IOG flags 0x3 (0x51) Please Help!

### ISSUE THREAD

**Issue by oronfel2911** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#19] opened 2022-03-10 17:44 UTC
Hello Sir.
I have the same model but 15inch, Lenovo yoga c740-15iml
Intel Core i5-10210U
Intel Graphics UHD 630
12GB Ram
Kingston NVME SSD 120GB
Wifi BCM94352Z

I tried to use your EFI But Stuck on IOG flags 0x3 (0x51) Please Help. 

![IMG_7312](https://user-images.githubusercontent.com/6498523/157723436-b1faf441-68ca-4d98-b0ee-fb71a917f30a.jpg)

**Comment by ThrRip** [comment] 2022-03-10 18:00
Hi there,

I guess this is caused by incorrect iGPU-related configs. Try to follow [this part of the guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#deviceproperties) and patch the framebuffer on your own.

**Comment by oronfel2911** [comment] 2022-03-10 21:52
Hello SIr. 
I did it and am still stuck on this page. 
![IMG_7313](https://user-images.githubusercontent.com/6498523/157760755-d1950e40-8264-4363-a79b-ec6d83f2b7f2.png)

**Comment by ThrRip** [comment] 2022-03-10 22:11
> Hello SIr. I did it and am still stuck on this page. ![IMG_7313](https://user-images.githubusercontent.com/6498523/157760755-d1950e40-8264-4363-a79b-ec6d83f2b7f2.png)

Unfortunately it's now sleep time for me. Going to figure out the problem in my dream 😄

**Comment by oronfel2911** [comment] 2022-03-10 22:17
OK, sorry for bothering you, any update Sir.?

**Comment by ThrRip** [comment] 2022-03-11 15:54
I guess you should remove all kexts start with `SMC` for now, and add them back when the OS is installed.

**Comment by oronfel2911** [comment] 2022-03-11 15:55
I will try that, thank you?

**Comment by oronfel2911** [comment] 2022-03-11 18:39
No luck Stuck still, Any Advice?
![IMG_7317](https://user-images.githubusercontent.com/6498523/157931475-1c6ae81d-f6b6-4953-af7b-2d9de167e456.png)

**Comment by oronfel2911** [comment] 2022-03-12 15:52
Any news sir

**Comment by ThrRip** [comment] 2022-03-12 16:13
So this is my opinion - most likely it's caused by one of the following two reasons:
- The frame buffer is unable to be fully patched through OpenCore _on your machine_, which leads us to patch the BIOS directly, to force set the **DVMT pre-allocated** value to 64MB (possibly you can only set it to 32MB in either the BIOS or OpenCore).
  > This is a known issue on Lenovo Yoga C740-14IML, I followed [this guide](https://zhuanlan.zhihu.com/p/266400995) (sorry but Chinese only) to do the stuff I mentioned above and solved this problem.
- Because your machine is not exactly the same as mine, it may have **different ACPI device mapping**, this way you have to create almost all SSDTs for your own situation. A great guide: [Getting Started With ACPI](https://dortania.github.io/Getting-Started-With-ACPI/).

You may want to try both of these two solutions, maybe the SSDT one first because I personally think that's easier.

**Comment by oronfel2911** [comment] 2022-03-18 19:09
finally, I got Monterey to work, just have a few issues if you could help. 
Airdrop not working. 
Touch screen not working. 
laptop doesn't wakeup after sleep

Can you guide me on how to fix both and add patching of XOSI, patching VoodooI2CPCIController.cpp

**Comment by ThrRip** [comment] 2022-03-18 19:55
> Airdrop not working.

This machine comes with an Intel wireless adapter, and it's impossible to get Airdrop working with it at this moment.

> Touch screen not working.

When I was on Big Sur 11, it worked with those configurations in the [macos-11](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/tree/macos-11) branch but only after closing up and reopening the laptop. However, this workaround does nothing on Monterey.

> Can you guide me on how to fix both and add patching of XOSI, ...

All DSDT/SSDT-related help information is included in the guide [_Getting Started With ACPI_](https://dortania.github.io/Getting-Started-With-ACPI/), which I already mentioned in [my last reply](#issuecomment-1065910262).

> ... patching VoodooI2CPCIController.cpp

This is the guide I followed: [_Using VoodooI2C on comet lake cpu (e.g: i5-10210u)_](https://www.notion.so/Using-VoodooI2C-on-comet-lake-cpu-e-g-i5-10210u-142930887087445eaa533120455da5dc).

**Comment by oronfel2911** [comment] 2022-03-18 20:41
Thank you so much. i Gotta you, 
you are the best. do you have any idea how to fix sleep issue, doesn't wake after sleep 

Thanks

**Comment by ThrRip** [comment] 2022-03-18 20:44
> do you have any idea how to fix sleep issue, doesn't wake after sleep

Sorry, I have no idea about this, because I'm not experiencing any sleep issues.

**Comment by starxxy** [comment] 2022-04-05 05:55
Hello sir, I also encountered the same problem, can you tell me how to solve this problem ?

**Comment by starxxy** [comment] 2022-04-05 05:56
> 太感谢了。我要你， 你是最棒的。你知道如何解决睡眠问题，睡后不醒来
> 
> 谢谢



> Thank you so much. i Gotta you, you are the best. do you have any idea how to fix sleep issue, doesn't wake after sleep
> 
> Thanks

Hello sir, I also encountered the same problem, can you tell me how to solve this problem ?

**Comment by starxxy** [comment] 2022-04-05 05:57
> finally, I got Monterey to work, just have a few issues if you could help. 
> Airdrop not working. 
> Touch screen not working. 
> laptop doesn't wakeup after sleep
>
> Can you guide me on how to fix both and add patching of XOSI, patching VoodooI2CPCIController.cpp 

Hello sir, I also encountered the same problem, can you tell me how to solve this problem ?

**Comment by ThrRip** [comment] 2022-04-05 06:13
> > finally, I got Monterey to work, just have a few issues if you could help. 
> > Airdrop not working. 
> > Touch screen not working. 
> > laptop doesn't wakeup after sleep
> >
> > Can you guide me on how to fix both and add patching of XOSI, patching VoodooI2CPCIController.cpp
> 
> Hello sir, I also encountered the same problem, can you tell me how to solve this problem ?

Have you really read [this comment by me](#issuecomment-1065910262) before you comment here like a dumb?

And also, what do you mean _**the same** problem_ and _**this** problem_? He mentioned literally three issues, do you mean you are experiencing all of them? If you want to get answers from others, you first need to describe your question clearly.

By the way, please disable your web page translator **before starting writing the comment** to avoid ruining the text and making everything difficult to read for others. **I edited your comment this time but likely wouldn't do it again.**

**Closed as completed** 2022-04-09 15:18 UTC
Labels: good first issue, kernel
